- README.md
> doc: Add clone cmd

- .gitignore
- docs/Makefile
- docs/source/index.rst
删除了gitignore中的MakeFile忽略项
提交了文档的构建makefile
> 修复文档的makefile

- .github/workflows/macos_arm.yml
- CMakeLists.txt
- README.md
> fix: windows doesn't support cmake config

- include/nndeploy/inference/ascend_cl/ascend_cl_inference.h
- source/nndeploy/inference/ascend_cl/ascend_cl_inference.cc
解决单一进程内，多线程多路视频流init时，aclInit api冲突报错问题
> fix mdc infer init conflict

- docs/zh_cn/quick_start/build.md
> update gcc version requirement to >= 5.1

- demo/test_op/demo.cc
- framework/include/nndeploy/op/op_rmsnorm.h
- framework/source/nndeploy/op/cuda/op_rmsnorm.cu
- framework/source/nndeploy/op/op.cc
- framework/source/nndeploy/op/op_rmsnorm.cc
- 添加rmsnorm CUDA kernel
- 添加op测试，并测试rmsnorm通过
-
> 添加 rmsnorm

- framework/source/nndeploy/inference/tensorrt/tensorrt_inference.cc
已修复inner_forward_buffer_指针和forward_memory_size_ 的初始化以及inner_forward_buffer_释放
> 已修复:inner_forward_buffer_指针初始化和释放bug

- framework/include/nndeploy/ir/op_param.h
- framework/include/nndeploy/net/optimizer.h
- framework/include/nndeploy/net/optimizer/fuse_conv_act.h
- framework/include/nndeploy/op/expr.h
- framework/source/nndeploy/net/optimizer/fuse_conv_act.cc
- framework/source/nndeploy/net/optimizer/fuse_conv_relu.cc
- framework/source/nndeploy/op/expr.cc
- framework/source/nndeploy/op/op_conv.cc
Pass fuse_conv_act 加conv param修改
> Pass fuse_conv_act 加conv param修改

- framework/include/nndeploy/net/tensor_pool/tensor_pool_1d.h
- framework/include/nndeploy/op/expr.h
- framework/source/nndeploy/net/tensor_pool/tensor_pool_1d.cc
- framework/source/nndeploy/op/expr.cc
- python/nndeploy/op/__init__.py
- python/nndeploy/op/expr.py
- python/nndeploy/tests/expr/test_resnet_0.py
- python/src/op/expr.cc
1. add、gemm、flatten等算子的makeExpr导出
2. 使用expr搭建resnet50的最后几层，并与pytorch对齐
3. 添加了没有任何内存重用优化的内存池
4.
> expr构建resnet的尾部

- framework/include/nndeploy/ir/default_interpret.h
- framework/include/nndeploy/ir/interpret.h
- framework/include/nndeploy/ir/onnx/onnx_interpret.h
- framework/source/nndeploy/ir/default_interpret.cc
- framework/source/nndeploy/ir/interpret.cc
- framework/source/nndeploy/ir/ir.cc
- framework/source/nndeploy/ir/onnx/onnx_interpret.cc
> Realtyxxx merge 0219

- cmake/config_ascendcl.cmake
add ENABLE_NNDEPLOY_OP_ASCEND_C compile tag
add new compile option
There are no side effects
add ENABLE_NNDEPLOY_OP_ASCEND_C into config_ascendcl.cmake
> add ascend_c op compile option

- demo/infer/demo.cc
- demo/inference/demo.cc
- demo/resnet/demo.cc
- framework/include/nndeploy/op/expr.h
- framework/source/nndeploy/op/expr.cc
- python/nndeploy/net/model.py
- python/nndeploy/op/__init__.py
- python/nndeploy/op/expr.py
- python/nndeploy/op/functional.py
- python/nndeploy/test/op/test_gemm_single_op.py
- python/nndeploy/test/op/test_softmax_single_op.py
- python/src/op/expr.cc
- python/src/op/op.cc
- python/src/op/op_func.cc
- python/src/op/op_func.h
增加Gemm与Softmax单算子模型Demo
规范化Softmax的大小写
- 
- 
- 
> Gemm与softmax单算子模型demo

- framework/source/nndeploy/net/optimizer/fuse_qdq.cc
- python/nndeploy/test/net/optimizer/test_constant_fold.py
- python/nndeploy/test/net/optimizer/test_eliminate_common_subexpression.py
- python/nndeploy/test/net/optimizer/test_eliminate_dead_op.py
- python/nndeploy/test/net/optimizer/test_fuse_conv_relu.py
- python/nndeploy/test/net/optimizer/test_fuse_conv_sigmoid.py
- python/src/device/tensor_util.cc
- python/src/net/net.cc
> Fix qdq bug && tensor double free bug

- demo/ascendc_dev/demo.cc
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_add_kernel.cc
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_add_kernel.h
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_conv_kernel.cc
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_conv_kernel.h
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_maxpool_kernel.cc
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_maxpool_kernel.h
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_mul_kernel.cc
- framework/source/nndeploy/op/ascend_cl/ascend_c/op_mul_kernel.h
- framework/source/nndeploy/op/ascend_cl/op_add.cc
- framework/source/nndeploy/op/ascend_cl/op_conv.cc
- framework/source/nndeploy/op/ascend_cl/op_maxpool.cc
- framework/source/nndeploy/op/ascend_cl/op_mul.cc
- python/nndeploy/test/op/ascendc/test_add.py
- python/nndeploy/test/op/ascendc/test_conv.py
- python/nndeploy/test/op/ascendc/test_mul.py
- python/nndeploy/test/op/test_conv_ascendcl.py
1. use custom ascend c add op to test detect infer
2. add float32 dtype support for add/mul/conv/maxpool op
No side effects
- 
- 
- 
Test each op impl and detect infer
> add op infer and float32 dtype support

- demo/llama/demo.cc
- demo/llama/llm.onnx.data
- demo/llama/test_llama2.sh
- plugin/include/nndeploy/llm/llama2.h
- plugin/source/nndeploy/llm/llama2.cc
recompile and run llama demo, fix compile and run error
There are no effects
- 
- 
- 
> Fix llama demo error

- docs/README.md
- framework/include/nndeploy/ir/onnx/onnx_interpret.h
- framework/include/nndeploy/ir/op_param.h
- framework/source/nndeploy/ir/onnx/onnx_bool_comparision_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_cast_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_constantofshape_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_expand_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_gather_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_interpret.cc
- framework/source/nndeploy/ir/onnx/onnx_neg_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_reduce_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_shape_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_sqrt_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_trig_func_convert.cc
- framework/source/nndeploy/ir/onnx/onnx_unsqueeze_convert.cc
- framework/source/nndeploy/ir/op_param.cc
> Qwen  onnx convert

- README.md
- README_EN.md
update discord link and Englsih readme file
> Update discord link and English readme file

- docs/zh_cn/quick_start/model_list.md
> Update Model Lists

- python/nndeploy/test/expr/test_alexnet.py
- python/nndeploy/test/expr/test_resnet_0.py
- python/nndeploy/test/net/model_zoo/test_resnet.py
- python/nndeploy/test/net/optimizer/test_constant_fold.py
- python/nndeploy/test/net/optimizer/test_eliminate_common_subexpression.py
- python/nndeploy/test/net/optimizer/test_eliminate_dead_op.py
- python/nndeploy/test/net/optimizer/test_fuse_conv_relu.py
- python/nndeploy/test/net/optimizer/test_fuse_conv_sigmoid.py
- python/nndeploy/test/op/ascendc/test_add.py
- python/nndeploy/test/op/ascendc/test_conv.py
- python/nndeploy/test/op/ascendc/test_maxpool.py
- python/nndeploy/test/op/ascendc/test_mul.py
- python/nndeploy/test/op/test.py
- python/nndeploy/test/op/test_activation.py
- python/nndeploy/test/op/test_add_ascendcl.py
- python/nndeploy/test/op/test_batch_norm_ascendcl.py
- python/nndeploy/test/op/test_conv_ascendcl.py
- python/nndeploy/test/op/test_flatten.py
- python/nndeploy/test/op/test_gemm.py
- python/nndeploy/test/op/test_gemm_single_op.py
- python/nndeploy/test/op/test_global_averagepool.py
- python/nndeploy/test/op/test_maxpool.py
- python/nndeploy/test/op/test_mul.py
- python/nndeploy/test/op/test_qlinear_conv.py
- python/nndeploy/test/op/test_rms_norm.py
- python/nndeploy/test/op/test_softmax_single_op.py
- python/nndeploy/test/op/x86/test_conv.py
- python/nndeploy/test/tensor/test_numpy.py
- python/nndeploy/test/test_util/test_export.py
> fixed tensor.py

- server/app.py
- server/executor.py
- server/graph_runner.py
- server/server.py
- server/task_queue.py
- server/worker.py
When nndeploy backend execute failed (core dump), reload the worker, keep server alive
> nndeploy server backup impl

- plugin/include/nndeploy/segment/segment_anything/sam.h
- plugin/source/nndeploy/segment/segment_anything/sam.cc
- update segment anything plugin
- support use mouse to select segment points
- [√] Feature
- 
- 
- 
> [SAM] update segment anything plugin

- CMakeLists.txt
- framework/include/nndeploy/base/common.h
- framework/include/nndeploy/kernel/cuda/type.h
- framework/include/nndeploy/kernel/elementwise_unary_kernel.h
- framework/include/nndeploy/kernel/kernel.h
- framework/include/nndeploy/kernel/preprocessor_marco.h
- framework/include/nndeploy/kernel/scalar.h
- framework/include/nndeploy/kernel/unary_functor.h
- framework/include/nndeploy/kernel/util.h
- framework/source/nndeploy/base/common.cc
- framework/source/nndeploy/kernel/cuda/elementwise_unary_kernel.cu
- framework/source/nndeploy/kernel/scalar.cc
kernel工厂注册
unary kernel工厂实现
下一步实现unary kernel的launch，对应op的包装，python层的测试
- 
- 
- 
> kernel工厂注册

- demo/segment_anything/demo.cc
- plugin/include/nndeploy/segment/segment_anything/sam.h
- plugin/source/nndeploy/segment/segment_anything/sam.cc
- python/nndeploy/segment/__init__.py
- python/nndeploy/segment/sam.py
- python/src/segment/segment_anything/segment_anything.cc
support sam dynamic graph
- 
- 
- 
> [SAM] support sam dynamic graph

- framework/include/nndeploy/device/tensor.h
- framework/source/nndeploy/device/arm/arm_device.cc
- framework/source/nndeploy/device/ascend_cl/ascend_cl_device.cc
- framework/source/nndeploy/device/cpu/cpu_device.cc
- framework/source/nndeploy/device/cuda/cuda_device.cc
- framework/source/nndeploy/device/type.cc
- framework/source/nndeploy/device/x86/x86_device.cc
[Tensor] support Tensor GetPtr API
- [√] Feature
- 
- 
- 
> [Tensor] support Tensor GetPtr API

- demo/ocr/README.md
- demo/ocr/demo.cc
- plugin/include/nndeploy/ocr/classifier.h
- plugin/include/nndeploy/ocr/clipper.h
- plugin/include/nndeploy/ocr/detector.h
- plugin/include/nndeploy/ocr/drawbox.h
- plugin/include/nndeploy/ocr/ocr.h
- plugin/include/nndeploy/ocr/ocr_postprocess_op.h
- plugin/include/nndeploy/ocr/recognizer.h
- plugin/include/nndeploy/ocr/result.h
- plugin/include/nndeploy/ocr/utils.h
- plugin/source/nndeploy/ocr/classifier.cc
- plugin/source/nndeploy/ocr/clipper.cc
- plugin/source/nndeploy/ocr/config.cmake
- plugin/source/nndeploy/ocr/detector.cc
- plugin/source/nndeploy/ocr/drawbox.cc
- plugin/source/nndeploy/ocr/ocr.cc
- plugin/source/nndeploy/ocr/ocr_postprocess_op.cc
- plugin/source/nndeploy/ocr/recognizer.cc
- python/src/ocr/ocr.cc
Use rapidjson instead of yaml-cpp and use clang-format format the code.
- [ x ] Refactoring
- [ x ] I have followed the project's coding guidelines.
- [ x ] I have tested my changes and ensured they work correctly.
- [ x ] I have merged the latest changes from the `main` branch and tested my code accordingly.
- [ x ] I have updated any relevant documentation.
- [ x ] I have provided clear and descriptive commit messages.
- [ x ] My code does not introduce new warnings or errors.
If this PR is related to an issue, please …
> fix:use rapidjson instead of yaml-cpp.use clang-format format the code.
